const handler = async (m, {conn}) => {
  m.reply(global.vv2);
};
handler.command = /^(vividos|vv2)$/i;
export default handler;
handler.admin = true
handler.group = true
handler.botAdmin = true

global.vv2 = `
1 SOPORTE  POR EQUIPO
NO EXPLOSIVOS
2 THIVA POR EQUIPO
NO ORION, NO SONIA, NO WUKONG, NO RAFAEL ( SOLO SOPORTE OCUPA RAFAEL ), NO ARAÑA.
1 OTHO POR EQUIPO
2 ROTACIONES POR EQUIPO
EN CASO DE NECESITAR REVISAR ALGUN JUGADOR SE HABLA Y QUE COMPARTA.
CREACION DE SALA:

ASPECTO GENERICO: SI
ATRIBUTOS DE ARMA: NO

ARMAS:
WEADPEAKER,TROGON,M1887,M1014,BIZON,AWM,XM8, MINI UZI,MP40, DESERT 

EN TODO CASO PUEDA SER TODOS CON TATSUYA INCLUYENDO SOPORTE O DIRRECTAMENTE CON HABILIDADES NORMALES```
`;
